apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "spring-petclinic.fullname" . }}
  labels:
    app: {{ template "spring-petclinic.name" . }}
    chart: {{ template "spring-petclinic.chart" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "spring-petclinic.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "spring-petclinic.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 40
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 40
