kind: Service
apiVersion: v1
metadata:
  name: {{ template "spring-petclinic.fullname" . }}
  labels:
    app: {{ template "spring-petclinic.name" . }}
    chart: {{ template "spring-petclinic.chart" . }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    external-dns.alpha.kubernetes.io/hostname: petclinic.glnkdev.com
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "spring-petclinic.name" . }}
